name: ghena_alshaam
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.4.6+114

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.2
  google_maps_place_picker:
    path: package/google_maps_place_picker-master
  get_storage: ^2.0.3
  dio: ^4.0.6
  flare_flutter: ^3.0.2
  video_player: ^2.4.0
  flutter_custom_clippers: ^2.0.0
  share: ^2.0.4
  lottie: ^1.3.0
  webview_flutter: ^3.0.2
  flutter_bloc: ^8.0.1
  marquee: ^2.2.1
  carousel_slider: ^4.1.1
  font_awesome_flutter: ^10.1.0
  google_maps_flutter: ^2.0.11
  equatable: ^2.0.5
  fading_edge_scrollview: ^3.0.0
  # google_map_location_picker: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^1.0.0


flutter_icons:
  image_path: 'assets/images/appicon.png'
  image_path_android: 'assets/images/appicon.png'
  image_path_ios: 'assets/images/appicon.png'
  android: true
  ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/flare/
    - assets/videos/
    - assets/lottie/
    - assets/images/products/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700